# k8s/workers-deployment.yaml
# Kubernetes deployment for BullMQ workers

apiVersion: apps/v1
kind: Deployment
metadata:
  name: budget-planner-workers
  namespace: default
  labels:
    app: budget-planner-workers
    tier: background-jobs
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: budget-planner-workers
  template:
    metadata:
      labels:
        app: budget-planner-workers
        tier: background-jobs
    spec:
      containers:
      - name: worker
        image: budget-planner:latest
        command: ["node", "scripts/start-workers-production.js"]
        ports:
        - containerPort: 3003
          name: health
        env:
        - name: NODE_ENV
          value: "production"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: budget-planner-secrets
              key: redis-url
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: budget-planner-secrets
              key: supabase-url
        - name: SUPABASE_SERVICE_ROLE_KEY
          valueFrom:
            secretKeyRef:
              name: budget-planner-secrets
              key: supabase-service-role-key
        - name: PLAID_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: budget-planner-secrets
              key: plaid-client-id
        - name: PLAID_SECRET
          valueFrom:
            secretKeyRef:
              name: budget-planner-secrets
              key: plaid-secret
        - name: PLAID_ENV
          value: "production"
        - name: WORKER_HEALTH_PORT
          value: "3003"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3003
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 15"]
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: budget-planner-workers-service
  labels:
    app: budget-planner-workers
spec:
  selector:
    app: budget-planner-workers
  ports:
  - name: health
    port: 3003
    targetPort: 3003
  type: ClusterIP

---
apiVersion: v1
kind: Secret
metadata:
  name: budget-planner-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  redis-url: <base64-encoded-redis-url>
  supabase-url: <base64-encoded-supabase-url>
  supabase-service-role-key: <base64-encoded-supabase-key>
  plaid-client-id: <base64-encoded-plaid-client-id>
  plaid-secret: <base64-encoded-plaid-secret>

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: budget-planner-workers-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: budget-planner-workers